### ISSUE TITLE
Fix Request Timeout

### ISSUE THREAD

**Issue by dodyac** [nfe-w/telegraph_downloader#1]
some file can't be downloaded, and stuck when processing

**Comment by nfe-w** [comment]
can you provide an example so that I can reproduce it

**Comment by dodyac** [comment]
https://telegra.ph/%E6%B0%B4%E6%B7%BC---%E9%BB%91%E6%B1%9F%E9%9B%ABShizuku-Tan-My-Dress-Up-Darling-05-24

**Comment by nfe-w** [comment]
I tried to download this url, but there was no error, could you take a screenshot of the error message

![](https://s2.loli.net/2022/05/26/apQDtzj86CfJT5O.png)

**Comment by dodyac** [comment]
![image](https://user-images.githubusercontent.com/37199748/170449107-85fbe7aa-22e4-4f69-8a79-a288030acb66.png)

**Comment by nfe-w** [comment]
I used python 3.9.10 and aiohttp 3.8.1 to run this file, I'm not sure if it's version related, but I suggest you can try again after upgrading aiohttp

**Comment by dodyac** [comment]
I'm using python 3.10 and aiohttp 3.8.1

**Comment by nfe-w** [comment]
I've added request headers, but I'm not sure if it has an effect

**Comment by dodyac** [comment]
it's still not working, were you able to download all those 40 files?

**Comment by nfe-w** [comment]
Yes, all 40 files downloaded successfully, maybe it's a network problem?🤔

<img width="500" alt="iShot_2022-05-26_17 47 11" src="https://user-images.githubusercontent.com/41944640/170463585-33b6ed89-4215-4dad-87bd-2b891405a1f1.png">

**Comment by dodyac** [comment]
i don't know, i have 500Mbps but still got some error, i tried to add timeout like 10s to the code and it shows connection timeout

**Comment by dodyac** [comment]
damn, i tried using vpn and it worked fine,

**Comment by dodyac** [comment]
damn, i tried using vpn and it worked fine,
